allowBuilds:
  '@clerk/shared': true
  esbuild: true
  sharp: true
  tesseract.js: set this to true or false
  workerd: true
onlyBuiltDependencies:
  - '@clerk/shared'
  - esbuild
  - sharp
  - workerd
